export const allCategories = [
	'Angular',
	'Architecture',
	'AWS',
	'DevOps',
	'Engineering Leadership',
	'GraphQL',
	'JavaScript',
	'Microservices',
	'Node.js',
	'Open Source',
	'Project Management',
	'ReactJS',
	'REST',
	'Serverless',
	'TypeScript',
] as const;
